In [3]:
import pandas as pd

In [4]:
pd.__version__

'2.3.1'

In [37]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [6]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [9]:
row_count = df.shape[0]
column_count = df.shape[1]
row_count, column_count

(9704, 11)

In [11]:
df["fuel_type"].unique()
df["fuel_type"].nunique()
df["fuel_type"].value_counts()

fuel_type
Gasoline    4898
Diesel      4806
Name: count, dtype: int64

In [16]:
(df.isna().sum() > 0).sum()
(df.isna().sum())

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [18]:
df['fuel_efficiency_mpg'][df['origin'] == 'Asia'].max()
df.loc[df['origin'] == 'Asia', 'fuel_efficiency_mpg'].max()

23.759122836520497

In [38]:
df['horsepower'].median()

149.0

In [39]:
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

In [40]:
# If horsepower might be strings, coerce to numeric first
df['horsepower'] = pd.to_numeric(df['horsepower'], errors='coerce')

# Compute the mode (handles ties) and take the first one
hp_mode = df['horsepower'].mode().iloc[0]

# Fill missing values with the mode
df['horsepower'] = df['horsepower'].fillna(hp_mode)

In [32]:
df['horsepower'].isna().sum()

np.int64(0)

In [41]:
df['horsepower'].median()

152.0

In [45]:
df.loc[df['origin'] == 'Asia',['vehicle_weight', 'model_year']].head(7)

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [48]:
X = df.loc[df['origin'] == 'Asia',['vehicle_weight', 'model_year']].head(7).to_numpy(dtype='float64')

In [49]:
X, X.shape

(array([[2714.21930965, 2016.        ],
        [2783.86897424, 2010.        ],
        [3582.68736772, 2007.        ],
        [2231.8081416 , 2011.        ],
        [2659.43145076, 2016.        ],
        [2844.22753389, 2014.        ],
        [3761.99403819, 2019.        ]]),
 (7, 2))

In [50]:
X.T

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [52]:
XTX = X.T @ X
XTX, XTX.shape

(array([[62248334.33150762, 41431216.5073268 ],
        [41431216.5073268 , 28373339.        ]]),
 (2, 2))

In [53]:
import numpy as np

In [55]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv, XTX_inv.shape

(array([[ 5.71497081e-07, -8.34509443e-07],
        [-8.34509443e-07,  1.25380877e-06]]),
 (2, 2))

In [57]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200], dtype='float64')
y, y.shape

(array([1100., 1300.,  800.,  900., 1000., 1100., 1200.]), (7,))

In [58]:
w = (XTX_inv @ X.T) @ y
w, w.shape

(array([0.01386421, 0.5049067 ]), (2,))

In [60]:
total = w.sum()
total

np.float64(0.5187709081074016)